[tool.poetry]
name = "synnax-freighter"
version = "0.38.0"
description = ""
authors = ["emiliano bonilla <emilbon99@gmail.com>"]
packages = [{ include = "freighter/**/*.py" }]

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
pytest-asyncio = "^0.25.2"
black = "^24.10.0"
mypy = "^1.14.1"
isort = "^5.13.2"

[tool.mypy]
ignore_missing_imports = true
strict_optional = false

[tool.isort]
profile = "black"

[tool.poetry.dependencies]
python = "^3.11"
websockets = "^13.1"
msgpack = "^1.1.0"
urllib3 = "^2.3.0"
pydantic = "^1.10.21"
alamos = { path = "../../alamos/py", develop = true }
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
markers = [
    "ws: mark test as a websocket test",
    "http: mark test as an http test",
    "sync: mark test as a sync test",
]
