[tool.poetry]
name = "synnax-integration"
version = "0.23.0"
description = ""
authors = ["leo liu <leoliuhy@gmail.com>"]
packages = [{ include = "./*.py" }]

[tool.poetry.dependencies]
python = "^3.12"
synnax-freighter = { path = "../../freighter/py", develop = true }
alamos = { path = "../../alamos/py", develop = true }
synnax = { path = "../../client/py", develop = true }
numpy = "^2.2.2"

[tool.poetry.group.dev.dependencies]
black = "^24.10.0"
pytest = "^8.3.4"
pytest-asyncio = "^0.25.2"
mypy = "^1.14.1"
isort = "^5.13.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
