[tool.poetry]
name = "cesium benchmarking"
version = "0.25.1"
description = "Benchmarking framework for cesium"
keywords = ["Synnax", "Cesium"]
repository = "https://github.com/synnaxlabs/synnax"
homepage = "https://synnaxlabs.com"
authors = ["leo liu <leohliu@umich.edu>"]
packages = [{ include = "./*.py" }]
[tool.poetry.group.dev.dependencies]
jupyterlab = "^4.3.4"
black = "^24.10.0"

[tool.isort]
profile = "black"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2.3"
urllib3 = "^2.3.0"
numpy = "^2.2.2"
matplotlib = "^3.10.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
plugins = ["numpy.typing.mypy_plugin"]
ignore_missing_imports = true
